# Use the AlmaLinux 9 base image
FROM almalinux/9-base

# Set environment variables (optional)
ENV container developer

# Install developer tools (e.g., git, vim, python, specific compilers)
RUN dnf update -y && \
    dnf groupinstall -y "Development Tools" && \
    dnf install -y epel-release && \
    dnf install -y \
	sudo \
        git \ 
	wget \
	tmux \
        vim \ 
	zsh \
	python3-pip \ 
	python3-devel \
        libXpm-devel \
	mosh \
	iotop \
	nload \
	nano \
	powerline-fonts && \
	dnf clean all

RUN pip install --upgrade pip

RUN adduser PlayerOne -s /bin/zsh && \
    echo "PlayerOne ALL=(root) NOPASSWD:ALL" | tee -a /etc/sudoers.d/user && \
    chmod 0440 /etc/sudoers.d/user

RUN cd /home/PlayerOne && \
    sudo -u PlayerOne wget https://github.com/gutsche/docker-containers/raw/master/alma9_dev_container/setup.tgz && \
    sudo -u PlayerOne tar xzf setup.tgz && \
    sudo -u PlayerOne rm setup.tgz

CMD ["su", "-", "PlayerOne"]
